// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "go-app/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockNewsRepository is an autogenerated mock type for the NewsRepository type
type MockNewsRepository struct {
	mock.Mock
}

type MockNewsRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNewsRepository) EXPECT() *MockNewsRepository_Expecter {
	return &MockNewsRepository_Expecter{mock: &_m.Mock}
}

// AssignTopics provides a mock function with given fields: ctx, newsID, topicIDs
func (_m *MockNewsRepository) AssignTopics(ctx context.Context, newsID uuid.UUID, topicIDs []uuid.UUID) error {
	ret := _m.Called(ctx, newsID, topicIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignTopics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, newsID, topicIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNewsRepository_AssignTopics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignTopics'
type MockNewsRepository_AssignTopics_Call struct {
	*mock.Call
}

// AssignTopics is a helper method to define mock.On call
//   - ctx context.Context
//   - newsID uuid.UUID
//   - topicIDs []uuid.UUID
func (_e *MockNewsRepository_Expecter) AssignTopics(ctx interface{}, newsID interface{}, topicIDs interface{}) *MockNewsRepository_AssignTopics_Call {
	return &MockNewsRepository_AssignTopics_Call{Call: _e.mock.On("AssignTopics", ctx, newsID, topicIDs)}
}

func (_c *MockNewsRepository_AssignTopics_Call) Run(run func(ctx context.Context, newsID uuid.UUID, topicIDs []uuid.UUID)) *MockNewsRepository_AssignTopics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]uuid.UUID))
	})
	return _c
}

func (_c *MockNewsRepository_AssignTopics_Call) Return(_a0 error) *MockNewsRepository_AssignTopics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNewsRepository_AssignTopics_Call) RunAndReturn(run func(context.Context, uuid.UUID, []uuid.UUID) error) *MockNewsRepository_AssignTopics_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNews provides a mock function with given fields: ctx, req
func (_m *MockNewsRepository) CreateNews(ctx context.Context, req *domain.CreateNewsRequest) (*domain.News, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateNews")
	}

	var r0 *domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateNewsRequest) (*domain.News, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateNewsRequest) *domain.News); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateNewsRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsRepository_CreateNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNews'
type MockNewsRepository_CreateNews_Call struct {
	*mock.Call
}

// CreateNews is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.CreateNewsRequest
func (_e *MockNewsRepository_Expecter) CreateNews(ctx interface{}, req interface{}) *MockNewsRepository_CreateNews_Call {
	return &MockNewsRepository_CreateNews_Call{Call: _e.mock.On("CreateNews", ctx, req)}
}

func (_c *MockNewsRepository_CreateNews_Call) Run(run func(ctx context.Context, req *domain.CreateNewsRequest)) *MockNewsRepository_CreateNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CreateNewsRequest))
	})
	return _c
}

func (_c *MockNewsRepository_CreateNews_Call) Return(_a0 *domain.News, _a1 error) *MockNewsRepository_CreateNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsRepository_CreateNews_Call) RunAndReturn(run func(context.Context, *domain.CreateNewsRequest) (*domain.News, error)) *MockNewsRepository_CreateNews_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNews provides a mock function with given fields: ctx, id
func (_m *MockNewsRepository) DeleteNews(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNews")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockNewsRepository_DeleteNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNews'
type MockNewsRepository_DeleteNews_Call struct {
	*mock.Call
}

// DeleteNews is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNewsRepository_Expecter) DeleteNews(ctx interface{}, id interface{}) *MockNewsRepository_DeleteNews_Call {
	return &MockNewsRepository_DeleteNews_Call{Call: _e.mock.On("DeleteNews", ctx, id)}
}

func (_c *MockNewsRepository_DeleteNews_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNewsRepository_DeleteNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockNewsRepository_DeleteNews_Call) Return(_a0 error) *MockNewsRepository_DeleteNews_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockNewsRepository_DeleteNews_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockNewsRepository_DeleteNews_Call {
	_c.Call.Return(run)
	return _c
}

// GetNews provides a mock function with given fields: ctx, id
func (_m *MockNewsRepository) GetNews(ctx context.Context, id uuid.UUID) (*domain.News, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetNews")
	}

	var r0 *domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.News, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.News); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsRepository_GetNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNews'
type MockNewsRepository_GetNews_Call struct {
	*mock.Call
}

// GetNews is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockNewsRepository_Expecter) GetNews(ctx interface{}, id interface{}) *MockNewsRepository_GetNews_Call {
	return &MockNewsRepository_GetNews_Call{Call: _e.mock.On("GetNews", ctx, id)}
}

func (_c *MockNewsRepository_GetNews_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockNewsRepository_GetNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockNewsRepository_GetNews_Call) Return(_a0 *domain.News, _a1 error) *MockNewsRepository_GetNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsRepository_GetNews_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.News, error)) *MockNewsRepository_GetNews_Call {
	_c.Call.Return(run)
	return _c
}

// GetNewsList provides a mock function with given fields: ctx, filter
func (_m *MockNewsRepository) GetNewsList(ctx context.Context, filter *domain.NewsFilter) ([]domain.News, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetNewsList")
	}

	var r0 []domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NewsFilter) ([]domain.News, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.NewsFilter) []domain.News); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.NewsFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsRepository_GetNewsList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNewsList'
type MockNewsRepository_GetNewsList_Call struct {
	*mock.Call
}

// GetNewsList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.NewsFilter
func (_e *MockNewsRepository_Expecter) GetNewsList(ctx interface{}, filter interface{}) *MockNewsRepository_GetNewsList_Call {
	return &MockNewsRepository_GetNewsList_Call{Call: _e.mock.On("GetNewsList", ctx, filter)}
}

func (_c *MockNewsRepository_GetNewsList_Call) Run(run func(ctx context.Context, filter *domain.NewsFilter)) *MockNewsRepository_GetNewsList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.NewsFilter))
	})
	return _c
}

func (_c *MockNewsRepository_GetNewsList_Call) Return(_a0 []domain.News, _a1 error) *MockNewsRepository_GetNewsList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsRepository_GetNewsList_Call) RunAndReturn(run func(context.Context, *domain.NewsFilter) ([]domain.News, error)) *MockNewsRepository_GetNewsList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNews provides a mock function with given fields: ctx, id, req
func (_m *MockNewsRepository) UpdateNews(ctx context.Context, id uuid.UUID, req *domain.UpdateNewsRequest) (*domain.News, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNews")
	}

	var r0 *domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateNewsRequest) (*domain.News, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateNewsRequest) *domain.News); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.News)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.UpdateNewsRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockNewsRepository_UpdateNews_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNews'
type MockNewsRepository_UpdateNews_Call struct {
	*mock.Call
}

// UpdateNews is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req *domain.UpdateNewsRequest
func (_e *MockNewsRepository_Expecter) UpdateNews(ctx interface{}, id interface{}, req interface{}) *MockNewsRepository_UpdateNews_Call {
	return &MockNewsRepository_UpdateNews_Call{Call: _e.mock.On("UpdateNews", ctx, id, req)}
}

func (_c *MockNewsRepository_UpdateNews_Call) Run(run func(ctx context.Context, id uuid.UUID, req *domain.UpdateNewsRequest)) *MockNewsRepository_UpdateNews_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*domain.UpdateNewsRequest))
	})
	return _c
}

func (_c *MockNewsRepository_UpdateNews_Call) Return(_a0 *domain.News, _a1 error) *MockNewsRepository_UpdateNews_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockNewsRepository_UpdateNews_Call) RunAndReturn(run func(context.Context, uuid.UUID, *domain.UpdateNewsRequest) (*domain.News, error)) *MockNewsRepository_UpdateNews_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNewsRepository creates a new instance of MockNewsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNewsRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNewsRepository {
	mock := &MockNewsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
