// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "go-app/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTopicRepository is an autogenerated mock type for the TopicRepository type
type MockTopicRepository struct {
	mock.Mock
}

type MockTopicRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTopicRepository) EXPECT() *MockTopicRepository_Expecter {
	return &MockTopicRepository_Expecter{mock: &_m.Mock}
}

// CreateTopic provides a mock function with given fields: ctx, req
func (_m *MockTopicRepository) CreateTopic(ctx context.Context, req *domain.CreateTopicRequest) (*domain.Topic, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateTopic")
	}

	var r0 *domain.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateTopicRequest) (*domain.Topic, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.CreateTopicRequest) *domain.Topic); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.CreateTopicRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_CreateTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTopic'
type MockTopicRepository_CreateTopic_Call struct {
	*mock.Call
}

// CreateTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - req *domain.CreateTopicRequest
func (_e *MockTopicRepository_Expecter) CreateTopic(ctx interface{}, req interface{}) *MockTopicRepository_CreateTopic_Call {
	return &MockTopicRepository_CreateTopic_Call{Call: _e.mock.On("CreateTopic", ctx, req)}
}

func (_c *MockTopicRepository_CreateTopic_Call) Run(run func(ctx context.Context, req *domain.CreateTopicRequest)) *MockTopicRepository_CreateTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.CreateTopicRequest))
	})
	return _c
}

func (_c *MockTopicRepository_CreateTopic_Call) Return(_a0 *domain.Topic, _a1 error) *MockTopicRepository_CreateTopic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_CreateTopic_Call) RunAndReturn(run func(context.Context, *domain.CreateTopicRequest) (*domain.Topic, error)) *MockTopicRepository_CreateTopic_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTopic provides a mock function with given fields: ctx, id
func (_m *MockTopicRepository) DeleteTopic(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTopic")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTopicRepository_DeleteTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTopic'
type MockTopicRepository_DeleteTopic_Call struct {
	*mock.Call
}

// DeleteTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTopicRepository_Expecter) DeleteTopic(ctx interface{}, id interface{}) *MockTopicRepository_DeleteTopic_Call {
	return &MockTopicRepository_DeleteTopic_Call{Call: _e.mock.On("DeleteTopic", ctx, id)}
}

func (_c *MockTopicRepository_DeleteTopic_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTopicRepository_DeleteTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTopicRepository_DeleteTopic_Call) Return(_a0 error) *MockTopicRepository_DeleteTopic_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTopicRepository_DeleteTopic_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTopicRepository_DeleteTopic_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopic provides a mock function with given fields: ctx, id
func (_m *MockTopicRepository) GetTopic(ctx context.Context, id uuid.UUID) (*domain.Topic, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTopic")
	}

	var r0 *domain.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Topic, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Topic); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_GetTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopic'
type MockTopicRepository_GetTopic_Call struct {
	*mock.Call
}

// GetTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTopicRepository_Expecter) GetTopic(ctx interface{}, id interface{}) *MockTopicRepository_GetTopic_Call {
	return &MockTopicRepository_GetTopic_Call{Call: _e.mock.On("GetTopic", ctx, id)}
}

func (_c *MockTopicRepository_GetTopic_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTopicRepository_GetTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTopicRepository_GetTopic_Call) Return(_a0 *domain.Topic, _a1 error) *MockTopicRepository_GetTopic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_GetTopic_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Topic, error)) *MockTopicRepository_GetTopic_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopicList provides a mock function with given fields: ctx, filter
func (_m *MockTopicRepository) GetTopicList(ctx context.Context, filter *domain.TopicFilter) ([]domain.Topic, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetTopicList")
	}

	var r0 []domain.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TopicFilter) ([]domain.Topic, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.TopicFilter) []domain.Topic); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.TopicFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_GetTopicList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopicList'
type MockTopicRepository_GetTopicList_Call struct {
	*mock.Call
}

// GetTopicList is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *domain.TopicFilter
func (_e *MockTopicRepository_Expecter) GetTopicList(ctx interface{}, filter interface{}) *MockTopicRepository_GetTopicList_Call {
	return &MockTopicRepository_GetTopicList_Call{Call: _e.mock.On("GetTopicList", ctx, filter)}
}

func (_c *MockTopicRepository_GetTopicList_Call) Run(run func(ctx context.Context, filter *domain.TopicFilter)) *MockTopicRepository_GetTopicList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.TopicFilter))
	})
	return _c
}

func (_c *MockTopicRepository_GetTopicList_Call) Return(_a0 []domain.Topic, _a1 error) *MockTopicRepository_GetTopicList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_GetTopicList_Call) RunAndReturn(run func(context.Context, *domain.TopicFilter) ([]domain.Topic, error)) *MockTopicRepository_GetTopicList_Call {
	_c.Call.Return(run)
	return _c
}

// GetTopicsByIDs provides a mock function with given fields: ctx, ids
func (_m *MockTopicRepository) GetTopicsByIDs(ctx context.Context, ids []uuid.UUID) ([]domain.Topic, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for GetTopicsByIDs")
	}

	var r0 []domain.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]domain.Topic, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []domain.Topic); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_GetTopicsByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTopicsByIDs'
type MockTopicRepository_GetTopicsByIDs_Call struct {
	*mock.Call
}

// GetTopicsByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockTopicRepository_Expecter) GetTopicsByIDs(ctx interface{}, ids interface{}) *MockTopicRepository_GetTopicsByIDs_Call {
	return &MockTopicRepository_GetTopicsByIDs_Call{Call: _e.mock.On("GetTopicsByIDs", ctx, ids)}
}

func (_c *MockTopicRepository_GetTopicsByIDs_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockTopicRepository_GetTopicsByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uuid.UUID))
	})
	return _c
}

func (_c *MockTopicRepository_GetTopicsByIDs_Call) Return(_a0 []domain.Topic, _a1 error) *MockTopicRepository_GetTopicsByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_GetTopicsByIDs_Call) RunAndReturn(run func(context.Context, []uuid.UUID) ([]domain.Topic, error)) *MockTopicRepository_GetTopicsByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTopic provides a mock function with given fields: ctx, id, req
func (_m *MockTopicRepository) UpdateTopic(ctx context.Context, id uuid.UUID, req *domain.UpdateTopicRequest) (*domain.Topic, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTopic")
	}

	var r0 *domain.Topic
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateTopicRequest) (*domain.Topic, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.UpdateTopicRequest) *domain.Topic); ok {
		r0 = rf(ctx, id, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Topic)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.UpdateTopicRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTopicRepository_UpdateTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTopic'
type MockTopicRepository_UpdateTopic_Call struct {
	*mock.Call
}

// UpdateTopic is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - req *domain.UpdateTopicRequest
func (_e *MockTopicRepository_Expecter) UpdateTopic(ctx interface{}, id interface{}, req interface{}) *MockTopicRepository_UpdateTopic_Call {
	return &MockTopicRepository_UpdateTopic_Call{Call: _e.mock.On("UpdateTopic", ctx, id, req)}
}

func (_c *MockTopicRepository_UpdateTopic_Call) Run(run func(ctx context.Context, id uuid.UUID, req *domain.UpdateTopicRequest)) *MockTopicRepository_UpdateTopic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*domain.UpdateTopicRequest))
	})
	return _c
}

func (_c *MockTopicRepository_UpdateTopic_Call) Return(_a0 *domain.Topic, _a1 error) *MockTopicRepository_UpdateTopic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTopicRepository_UpdateTopic_Call) RunAndReturn(run func(context.Context, uuid.UUID, *domain.UpdateTopicRequest) (*domain.Topic, error)) *MockTopicRepository_UpdateTopic_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTopicRepository creates a new instance of MockTopicRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTopicRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTopicRepository {
	mock := &MockTopicRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
