name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: my_project
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          cache: true
          cache-dependency-path: apps/go-app/go.sum

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup moon
        uses: moonrepo/setup-moon-action@v1

      - name: Install dependencies
        run: pnpm install

      - name: Install Mockery
        run: |
          go install github.com/vektra/mockery/v2@v2.52.2
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Run Tests with moon
        run: pnpm moon ci
        env:
          DATABASE_URL: postgres://user:password@localhost:5432/my_project?sslmode=disable
