with-expecter: true
packages:
  go-app/service:
    config:
      all: true
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: "mocks"
      filename: "{{.InterfaceName}}.go"
      structname: "{{.InterfaceName}}"
